services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: onboarding
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: onboarding_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
